import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:health_tracker/src/features/dashboard/dashboard_repository.dart';
import 'package:health_tracker/src/features/weight/weight_repository.dart';
import 'package:health_tracker/src/features/goals/goals_repository.dart';
import 'package:intl/intl.dart';

class ReportService {
  static Future<void> generateAndPrintReport({
    required List<DailyLog> dailyLogs,
    required List<WeightEntry> weightEntries,
    required GoalsState goals,
  }) async {
    final pdf = pw.Document();

    final today = DateFormat('yyyy-MM-dd').format(DateTime.now());
    
    // Calculate stats
    int workouts = dailyLogs.where((l) => l.workoutDone).length;
    double avgWater = dailyLogs.isEmpty ? 0 : dailyLogs.map((l) => l.waterIntake).reduce((a, b) => a + b) / dailyLogs.length;
    double avgCalories = dailyLogs.isEmpty ? 0 : dailyLogs.map((l) => l.caloriesBurned).reduce((a, b) => a + b) / dailyLogs.length;

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Personal Health Report', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                  pw.Text(today),
                ],
              ),
            ),
            pw.SizedBox(height: 20),
            pw.Container(
              padding: const pw.EdgeInsets.all(10),
              decoration: const pw.BoxDecoration(color: PdfColors.grey100),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                   pw.Row(
                     mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
                     children: [
                       _buildStatItem('Workouts (Last 7)', '$workouts days'),
                       _buildStatItem('Avg Water', '${avgWater.toInt()} ml/day'),
                       _buildStatItem('Avg Calories', '${avgCalories.toInt()} kcal/day'),
                     ]
                   )
                ]
              )
            ),
            pw.SizedBox(height: 20),
            pw.Text('Daily Activity (Last 7 Days)', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 10),
            pw.TableHelper.fromTextArray(
              headers: ['Date', 'Sugar Cut', 'Workout', 'Calories', 'Water (ml)'],
              data: dailyLogs.map((l) => [
                l.date,
                l.sugarCutCompleted ? 'Yes' : 'No',
                l.workoutDone ? 'Yes' : 'No',
                l.caloriesBurned.toString(),
                l.waterIntake.toString(),
              ]).toList(),
            ),
            pw.SizedBox(height: 30),
            pw.Text('Weight History', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 10),
            pw.TableHelper.fromTextArray(
              headers: ['Date', 'Weight (${goals.weightUnit})'],
              data: weightEntries.map((w) => [
                w.date,
                w.weight.toString(),
              ]).toList(),
            ),
            pw.Footer(
              margin: const pw.EdgeInsets.only(top: 20),
              trailing: pw.Text('Generated by Health Tracker App'),
            )
          ];
        },
      ),
    );

    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }

  static pw.Widget _buildStatItem(String label, String value) {
    return pw.Column(
      children: [
        pw.Text(label, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
        pw.Text(value, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
      ],
    );
  }
}
